name: ReturnNames
description: 'Take info from repo and make useable names from it.'
  
outputs:
  RepoName: 
    description: 'Name of the Repo'
    value: "${{ steps.RepoName.outputs._1 }}"
  Owner: 
    description: 'User or Org from Repo'
    value:  "${{ steps.RepoName.outputs._0 }}"
  SolutionName: 
    description: 'Name of the Solution'
    value:  "${{ steps.Find-sln.outputs.found }}"
#  PathToPackage: 
#    description: 'Path to the nupkg'
#    value:  "${{ steps.RepoName.outputs._1 }}/Path"
  Version:
    description:
    value: "${{ steps.get-version.outputs.version }}"

    
runs:
  using: "composite"
  steps:
  
  - uses: actions/checkout@v3

########################################################
#
#           Make RepoName and Owner outputs
#
########################################################

  - name: GetSplit - Repository
    uses: rishabhgupta/split-by@v1
    id: RepoName
    with:
        string: "${{ github.repository }}"
        split-by: "/"


########################################################
#
#           Find .csproj file, and version number
#
########################################################

  - name: Find csproj
    id: Find-csproj
    uses: DovnarAlexander/github-action-file-detection@master
    with:
      wildcard: '*.csproj'

  - name : get version from project
    uses: kzrnm/get-net-sdk-project-versions-action@v1
    id: get-version
    with:
      proj-path: "${{ steps.Find-csproj.outputs.found }}"

########################################################
#
#           Find .sln file
#
########################################################

  - name: Find sln
    id: Find-sln
    uses: DovnarAlexander/github-action-file-detection@master
    with:
      wildcard: '*.sln'
